### ISSUE TITLE
Leaderboard / tiers todo

### ISSUE THREAD

**Issue by Alex-At-Home** [Alex-At-Home/cbb-on-off-analyzer#139]
* [ ] Build all 3 tiers for 20/21
* [ ] Only show "Extra" for men/high tier
* [ ] Handle missing files more gracefully
* [ ] If missing year/tier specified, switch to high tier (hardcode this info)?
* [ ] Add tooltip to tier text
* [ ] Copy existing files to new format
