### ISSUE TITLE
On-Ball defense Phases 2+

### ISSUE THREAD

**Issue by Alex-At-Home** [Alex-At-Home/cbb-on-off-analyzer#173]
* [ ] Allow manual setting of on-ball (off-ball?) which just improves the DRtg in a vacuum
* [ ] Incorporate positional info if don't have Synergy stats
* [ ] Regress to get on-vs-off ball ratios (plus DRB weighting)
* [ ] Add to Team Report page

**Comment by Alex-At-Home** [comment]
Something seems wrong looking at least at this year's data ... the adjustment to make the manual numbers be in line with the actual average team DRtg is waaaaay too big

Need to look in more detail
