### ISSUE TITLE
Ideas for 21/22 season

### ISSUE THREAD

**Issue by Alex-At-Home** [Alex-At-Home/cbb-on-off-analyzer#181]
* [ ] Be able to import ShotQuality stats into editor
* [ ] Improve luck adjustments (assisted vs non-assisted; and allow user to specify regression)
* [ ] Game summary (lineup views etc)
* [ ] Game preview (calc efficiency adjustments per that Kenpom blog, calc play style defense)
* [ ] Scouting report for players
* [ ] Grades for players
* [ ] Edit team stats
* [ ] Allow player editor stats adjustments to apply to team stats
* [ ] Automation for women's efficiency

**Comment by Alex-At-Home** [comment]
Fixed issues

* [x] RAPM hell (https://github.com/Alex-At-Home/cbb-on-off-analyzer/pull/187)
   * [x] Back with "original value" on "luck adjusted" != "luck adjusted" eg [this query](http://localhost:3000/OnOffAnalyzer?autoOffQuery=false&baseQuery=date%3A%5B2021-12-06%20TO%20%2A%5D%20&calcRapm=true&gender=Men&maxRank=400&minRank=0&offQuery=&onOffLuck=true&onQuery=&possAsPct=false&showExpanded=true&showOnOffLuckDiags=true&team=Maryland&year=2021%2F22&)
   * [x] Aggregated luck adjustment now has 3P same with lineups, but off/def adj still a bit off (poss due to ORB?)
   * [x] Luck adj RAPM on subset still wrong - `compare observed (off=[8.48] def=[-1.15]) vs derived solely from RAPM (off=[9.52] def=[-0.60])` ... the RAPM shouldn't be able to be _higher_ unless the adj ratings are all wrong
