### ISSUE TITLE
Tidy up UI

### ISSUE THREAD

**Issue by Alex-At-Home** [Alex-At-Home/cbb-on-off-analyzer#89]
* [x] Remove bold for roster compare in on/off report
* [x] Improve line alignment (that trailing Adj is really annoying)
* [x] Decide whether to make it non-default
* [x] Move option into "advanced view"
* [x] Also make the on/off page have HTML key column
* [x] Improve individual on/off lineup
* [x] Move to On/A and Off/B verbiage
* [x] ~Fix annoying 2x browser history bug~ moved to #91
* [x] ~Jump back to right spot when making changes to filters etc~ _can't reproduce_
